name: butler

on:
  issue_comment:
    types: [created] # Someone comments on an issue or PR

permissions:
  pull-requests: write # This allows us to attach a comment to the PR, this is being applied to the workflow, not just a individual job

jobs:
  # log:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo 'comment ${{ github.event.comment.body }}'
  #     - run: echo '${{ toJson(github.event) }}'
  chat:
    if: contains(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - uses: ca-dp/code-butler@v1
        with: # Set the inputs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # I don't have an OPENAI_API_KEY secret
          cmd: chat
          comment_body: ${{ github.event.comment.body }}
  review:
    if: contains(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    steps:
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          cmd: review # This is the command that the butler will run