name: integration-tests

on:
    push:
      paths:
        - ".github/workflows/integration-tests.yml"
    workflow_dispatch: # manually trigger the workflow

jobs:
    generate:
        outputs:
            RANDOM_PASSWORD: ${{ env.RANDOM_PASSWORD }}
        runs-on: ubuntu-latest
        steps:
            - run: env | sort
            - run: echo "RANDOM_PASSWORD=$(LC_ALL=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 12)" >> $GITHUB_ENV
            - run: echo "RANDOM_PASSWORD / ${{ env.RANDOM_PASSWORD }}"
            - run: env | sort
            # - run: mysql ... -p $RANDOM_PASSWORD
    testing:
        runs-on: ubuntu-latest
        needs: generate
        container:
            image: mysql:8.4 # this is known as a job container
        steps:
            - run: echo " ${{ needs.generate.outputs.RANDOM_PASSWORD }}"
            - run: mysql --version

