name: upper-build

on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'upper/**'
    workflow_dispatch: # manually trigger a workflow
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: go version
