name: upper-capture

on:
    push:
        paths:
            - '.github/workflows/upper-capture.yml'
            - 'upper/**'
    workflow_dispatch: # manually trigger a workflow
    
jobs:
    capture:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest] # This means it will run 3 times, once for each OS
      runs-on: ${{ matrix.os }}
      defaults:
            run:
                working-directory: upper # change the working directory to the upper directory, for all steps
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with: # use this to pass parameters to the action
            go-version: '1.22'
            cache-dependency-path: ./upper/go.sum # this causes it to cache the go.sum file
        - run: ls
        - run: go build
        - run: ls
        - run: go test -v
        - uses: actions/upload-artifact@v4
          with:
            path: ./upper/upper
            name: build