name: upper-capture

on:
    push:
        paths:
            - '.github/workflows/upper-capture.yml'
            - 'upper/**'
    workflow_dispatch: # manually trigger a workflow
    
jobs:
    build:
        runs-on: macos-latest

        steps:
            - run: pwd && ls -la # check the current directory and list all files before
            - uses: actions/checkout@v4
            - run: pwd && ls -la # check the current directory and list all files after
            # - run: go version # check the go version before
            - uses: actions/setup-go@v5
              with: # use this to pass parameters to the action
                # go-version: '1.22'
                go-version-file: ./upper/go.mod # this causes it to read that go.mod file
                cache-dependency-path: ./upper/go.sum # this causes it to cache the go.sum file
            - run: go mod download # download the dependencies
              working-directory: upper # change the working directory to the upper directory
            - run: ls
            - run: go build
            - run: ls
            - run: go test -v
            