name: upper-cross

on:
    push:
        paths:
            - '.github/workflows/upper-cross.yml'
            - 'upper/**'
    workflow_dispatch: # manually trigger a workflow
    
jobs:
    cross:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      defaults:
            run:
                working-directory: upper # change the working directory to the upper directory, for all steps
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with: # use this to pass parameters to the action
            go-version: 1.22
            cache-dependency-path: ./upper/go.sum # this causes it to cache the go.sum file
        - run: ./build.xplat.sh
        - uses: softprops/action-gh-release@v2 # This action creates a release on GitHub
          with:
            files: ./upper/bin/upper*
            body: "Binaries for the upper (go) command line tool"
            tag_name: ${{ github.ref_name }} # GitHub Releases depend upon tags
        # - uses: actions/upload-artifact@v4
        #   with:
        #     path: ./upper/bin/upper*
        #     name: build