name: upper-build

on:
    push:
        paths:
            - '.github/workflows/upper-build.yml'
            - 'upper/**'
    workflow_dispatch: # manually trigger a workflow
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - run: pwd && ls -la # check the current directory and list all files before
            - uses: actions/checkout@v4
            - run: pwd && ls -la # check the current directory and list all files after
            - run: go version # check the go version before
            - uses: actions/setup-go@v5
              with: # use this to pass parameters to the action
                go-version: '1.22'
            - run: go version # check the go version after
            - run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar